# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 650)
        MainWindow.setMinimumSize(QtCore.QSize(400, 650))
        MainWindow.setMaximumSize(QtCore.QSize(400, 650))
        MainWindow.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 650))
        self.frame.setMinimumSize(QtCore.QSize(400, 650))
        self.frame.setMaximumSize(QtCore.QSize(400, 650))
        self.frame.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("background-color: rgb(236, 236, 236);\n"
"font: 87 25pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.clearButton = QtWidgets.QPushButton(self.frame_6)
        self.clearButton.setMinimumSize(QtCore.QSize(50, 100))
        self.clearButton.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_5.addWidget(self.clearButton)
        self.percentageButton = QtWidgets.QPushButton(self.frame_6)
        self.percentageButton.setMinimumSize(QtCore.QSize(50, 100))
        self.percentageButton.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.percentageButton.setObjectName("percentageButton")
        self.horizontalLayout_5.addWidget(self.percentageButton)
        self.backsapceButton = QtWidgets.QPushButton(self.frame_6)
        self.backsapceButton.setMinimumSize(QtCore.QSize(50, 100))
        self.backsapceButton.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.backsapceButton.setObjectName("backsapceButton")
        self.horizontalLayout_5.addWidget(self.backsapceButton)
        self.divisionButton = QtWidgets.QPushButton(self.frame_6)
        self.divisionButton.setMinimumSize(QtCore.QSize(50, 100))
        self.divisionButton.setStyleSheet("font: 87 24pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.divisionButton.setObjectName("divisionButton")
        self.horizontalLayout_5.addWidget(self.divisionButton)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seteButton = QtWidgets.QPushButton(self.frame_2)
        self.seteButton.setEnabled(True)
        self.seteButton.setMinimumSize(QtCore.QSize(50, 100))
        self.seteButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.seteButton.setObjectName("seteButton")
        self.horizontalLayout.addWidget(self.seteButton)
        self.oitoButton = QtWidgets.QPushButton(self.frame_2)
        self.oitoButton.setEnabled(True)
        self.oitoButton.setMinimumSize(QtCore.QSize(50, 100))
        self.oitoButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.oitoButton.setObjectName("oitoButton")
        self.horizontalLayout.addWidget(self.oitoButton)
        self.noveButton = QtWidgets.QPushButton(self.frame_2)
        self.noveButton.setEnabled(True)
        self.noveButton.setMinimumSize(QtCore.QSize(50, 100))
        self.noveButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.noveButton.setObjectName("noveButton")
        self.horizontalLayout.addWidget(self.noveButton)
        self.multiplicacaoButton = QtWidgets.QPushButton(self.frame_2)
        self.multiplicacaoButton.setEnabled(True)
        self.multiplicacaoButton.setMinimumSize(QtCore.QSize(50, 100))
        self.multiplicacaoButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.multiplicacaoButton.setObjectName("multiplicacaoButton")
        self.horizontalLayout.addWidget(self.multiplicacaoButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.quatroButton = QtWidgets.QPushButton(self.frame_3)
        self.quatroButton.setEnabled(True)
        self.quatroButton.setMinimumSize(QtCore.QSize(50, 100))
        self.quatroButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.quatroButton.setObjectName("quatroButton")
        self.horizontalLayout_2.addWidget(self.quatroButton)
        self.cincoButton = QtWidgets.QPushButton(self.frame_3)
        self.cincoButton.setEnabled(True)
        self.cincoButton.setMinimumSize(QtCore.QSize(50, 100))
        self.cincoButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.cincoButton.setObjectName("cincoButton")
        self.horizontalLayout_2.addWidget(self.cincoButton)
        self.seisButton = QtWidgets.QPushButton(self.frame_3)
        self.seisButton.setEnabled(True)
        self.seisButton.setMinimumSize(QtCore.QSize(50, 100))
        self.seisButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.seisButton.setObjectName("seisButton")
        self.horizontalLayout_2.addWidget(self.seisButton)
        self.menosButton = QtWidgets.QPushButton(self.frame_3)
        self.menosButton.setEnabled(True)
        self.menosButton.setMinimumSize(QtCore.QSize(50, 100))
        self.menosButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.menosButton.setObjectName("menosButton")
        self.horizontalLayout_2.addWidget(self.menosButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.umButton = QtWidgets.QPushButton(self.frame_4)
        self.umButton.setEnabled(True)
        self.umButton.setMinimumSize(QtCore.QSize(50, 100))
        self.umButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.umButton.setObjectName("umButton")
        self.horizontalLayout_3.addWidget(self.umButton)
        self.doisButton = QtWidgets.QPushButton(self.frame_4)
        self.doisButton.setEnabled(True)
        self.doisButton.setMinimumSize(QtCore.QSize(50, 100))
        self.doisButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.doisButton.setObjectName("doisButton")
        self.horizontalLayout_3.addWidget(self.doisButton)
        self.tresButton = QtWidgets.QPushButton(self.frame_4)
        self.tresButton.setEnabled(True)
        self.tresButton.setMinimumSize(QtCore.QSize(50, 100))
        self.tresButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.tresButton.setObjectName("tresButton")
        self.horizontalLayout_3.addWidget(self.tresButton)
        self.maisButton = QtWidgets.QPushButton(self.frame_4)
        self.maisButton.setEnabled(True)
        self.maisButton.setMinimumSize(QtCore.QSize(50, 100))
        self.maisButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.maisButton.setObjectName("maisButton")
        self.horizontalLayout_3.addWidget(self.maisButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.zeroButton = QtWidgets.QPushButton(self.frame_5)
        self.zeroButton.setEnabled(True)
        self.zeroButton.setMinimumSize(QtCore.QSize(50, 100))
        self.zeroButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.zeroButton.setObjectName("zeroButton")
        self.horizontalLayout_4.addWidget(self.zeroButton)
        self.maisMenosButton = QtWidgets.QPushButton(self.frame_5)
        self.maisMenosButton.setEnabled(True)
        self.maisMenosButton.setMinimumSize(QtCore.QSize(50, 100))
        self.maisMenosButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.maisMenosButton.setObjectName("maisMenosButton")
        self.horizontalLayout_4.addWidget(self.maisMenosButton)
        self.pontoButton = QtWidgets.QPushButton(self.frame_5)
        self.pontoButton.setEnabled(True)
        self.pontoButton.setMinimumSize(QtCore.QSize(50, 100))
        self.pontoButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.pontoButton.setObjectName("pontoButton")
        self.horizontalLayout_4.addWidget(self.pontoButton)
        self.igualButton = QtWidgets.QPushButton(self.frame_5)
        self.igualButton.setEnabled(True)
        self.igualButton.setMinimumSize(QtCore.QSize(50, 100))
        self.igualButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 87 24pt \"Arial Black\";")
        self.igualButton.setObjectName("igualButton")
        self.horizontalLayout_4.addWidget(self.igualButton)
        self.verticalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora Python"))
        self.label.setText(_translate("MainWindow", "0"))
        self.clearButton.setText(_translate("MainWindow", "AC"))
        self.percentageButton.setText(_translate("MainWindow", "%"))
        self.backsapceButton.setText(_translate("MainWindow", "<<"))
        self.divisionButton.setText(_translate("MainWindow", "/"))
        self.seteButton.setText(_translate("MainWindow", "7"))
        self.oitoButton.setText(_translate("MainWindow", "8"))
        self.noveButton.setText(_translate("MainWindow", "9"))
        self.multiplicacaoButton.setText(_translate("MainWindow", "*"))
        self.quatroButton.setText(_translate("MainWindow", "4"))
        self.cincoButton.setText(_translate("MainWindow", "5"))
        self.seisButton.setText(_translate("MainWindow", "6"))
        self.menosButton.setText(_translate("MainWindow", "-"))
        self.umButton.setText(_translate("MainWindow", "1"))
        self.doisButton.setText(_translate("MainWindow", "2"))
        self.tresButton.setText(_translate("MainWindow", "3"))
        self.maisButton.setText(_translate("MainWindow", "+"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.maisMenosButton.setText(_translate("MainWindow", "+/-"))
        self.pontoButton.setText(_translate("MainWindow", "."))
        self.igualButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
